# В первой строке объявляется имя создаваемого контейнера.
# В одном YAML-файле можно определить несколько контейнеров
# (часто называемых сервисами на диалекте Compose).
identidock:
    # Ключ build сообщает Compose, что образ для данного контейнера должен быть создан из Dockerfile,
    # расположенного в текущем каталоге (.).
    # Каждое определение контейнера должно содержать либо ключ build, либо ключ image.
    # Для ключей image задается тег или идентификатор образа,
    # из которого создается контейнер, по аналогии с аргументом image в команде docker run.
    # build .
    build: .
    # Ключ ports полностью аналогичен аргументу -p в команде docker run
    # и служит для объявления открытых портов.
    # Здесь связывается порт 5000 в контейнере с портом 5000 на хосте.
    # Кавычки не обязательны, но рекомендуется их использование,
    # чтобы избежать вероятной путаницы при синтаксическом разборе YAML-выражений,
    # например 56:56 как числа в шестидесятиричной системе.
    ports:
    - "5000:5000"
    # Ключ environment полностью аналогичен аргументу -e в команде docker run
    # и служит для определения значений переменных среды в контейнере.
    # Здесь для переменной ENV определяется значение DEV,
    # чтобы запустить веб-сервер Flask в режиме разработки.
    environment:
    #ENV: DEV
    - ENV=DEV
    # Ключ volumes полностью аналогичен аргументу -v в команде docker run
    # и служит для определения томов.
    # Здесь определено монтирование подкаталога app из текущего каталога
    # на каталог /app внутри контейнера точно так же, как мы делали раньше,
    # чтобы можно было вносить изменения в код прямо с хоста.
    volumes:
    - ./app:/app
    # Объявление установления соединения из контейнера identidok с контейнером dnmonster.
    # Compose обеспечивает правильный порядок запуска контейнеров для установления соединения.
    links:
        - dnmonster
        # Директива установления соединения с контейнером Redis.
        - redis
# Определение нового контейнера dnmonster.
# Здесь достаточно сообщить Compose о необходимости использования образа
# amouat/dnmonster:1.0 из репозитория Docker Hub.
dnmonster:
    image: amouat/dnmonster:1.0
redis:
    # Создание контейнера Redis на основе официального образа.
    image: redis:3.0